# Generated by Django 3.1.4 on 2020-12-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sweat', models.FloatField(default=0)),
                ('cape', models.FloatField(default=0)),
                ('rh700', models.FloatField(default=0)),
            ],
        ),
    ]
